keltanas_page_homepage:
    path:  /
    defaults: { _controller: KeltanasPageBundle:Default:index }

keltanas_page_about:
    path:  /about
    defaults: { _controller: KeltanasPageBundle:Default:about }

keltanas_page_tag:
    path: /tag/{name}
    defaults: { _controller: KeltanasPageBundle:Tag:index }

keltanas_page_post:
    resource: "@KeltanasPageBundle/Resources/config/routing/post.yml"
    prefix:   /post
