parameters:
    keltanas_page.tags_handler.subscriber.class: keltanas\PageBundle\EventListener\TagsHandlerSubscriber

services:
    keltanas_page.tags_handler.subscriber:
        class: %keltanas_page.tags_handler.subscriber.class%
        calls:
            - ["setMarkdown", ["@markdown.parser"]]
        tags:
            - { name: kernel.event_subscriber }

