parameters:
    keltanas_page.tags_handler.subscriber.class: Keltanas\PageBundle\EventListener\TagsHandlerSubscriber

services:
    dbal.session_init.listener:
        class: Doctrine\DBAL\Event\Listeners\MysqlSessionInit
        tags:
            - { name: doctrine.event_listener, event: postConnect }

    keltanas_page.tags_handler.subscriber:
        class: %keltanas_page.tags_handler.subscriber.class%
        calls:
            - ["setMarkdown", ["@markdown.parser"]]
        tags:
            - { name: kernel.event_subscriber }

    session.memcached:
        class: Memcached
        calls:
            - [ addServer, [ %session_memcached_host%, %session_memcached_port% ]]

    session.handler.memcached:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: [ @session.memcached, { prefix: %session_memcached_prefix%, expiretime: %session_memcached_expire% } ]

