parameters:
#    keltanas_user.example.class: Keltanas\Bundle\UserBundle\Example

services:
#    keltanas_user.example:
#        class: %keltanas_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
