stages:
  - composer
  - test

image: registry.ermin.ru/keltanas/siteforever-test-runner:7.2

services:
  - name: mysql:5.7
    alias: mysql

variables:
  MYSQL_ROOT_PASSWORD: "null"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_USER: blog
  MYSQL_PASSWORD: blog
  MYSQL_DATABASE: symf_blog

composer:
  stage: composer
  before_script:
    - mkdir app/cache app/logs
    - chmod 777 app/cache app/logs
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
  script:
    - php composer.phar install --prefer-dist -o -n
  cache:
    key: $CI_PROJECT_NAME
    paths:
      - ./vendor
  artifacts:
    paths:
      - ./vendor
    expire_in: 7 day
    when: on_success

after_script:
  - php app/console --env=test -n doctrine:database:drop --force

test:
  stage: test
  variables:
    SYMFONY__DATABASE_DRIVER: pdo_mysql
    SYMFONY__DATABASE_HOST: mysql
    SYMFONY__DATABASE_PORT: 3306
    SYMFONY__DATABASE_USER: blog
    SYMFONY__DATABASE_PASSWORD: blog
    SYMFONY__DATABASE_NAME: symf_blog
  before_script:
    - php app/console --env=test -n doctrine:database:create
    - php app/console --env=test -n doctrine:schema:create
    - php app/console --env=test -n -v doctrine:fixtures:load
  script:
    - php bin/behat
  dependencies:
    - composer
