language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
#  allow_failures:
#    - php: 5.6

before_install:
  - echo "memory_limit = 2G" > /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/z.ini

before_script:
  - mkdir app/cache app/logs
  - chmod 777 app/cache app/logs
  - composer install -n -o --prefer-dist --profile
  - sleep 3

script:
  - ./app/console --env=test -n doctrine:database:create
  - ./app/console --env=test -n doctrine:schema:create
  - ./app/console --env=test -n -v doctrine:fixtures:load
  - ./bin/behat
  - ./app/console --env=test -n doctrine:database:drop --force
