language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - mkdir app/cache app/logs
  - chmod 777 app/cache app/logs
  - composer install -n -o --prefer-dist
  - sleep 3

script:
  - ./app/console --env=test -n doctrine:database:create --if-not-exists
  - ./app/console --env=test -n doctrine:schema:create
  - ./app/console --env=test -n -v doctrine:fixtures:load
  - ./bin/behat
  - ./app/console --env=test -n doctrine:database:drop --if-exists --force
