<?php

namespace Keltanas\Bundle\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @return mixed
     */
    public function getCount()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select($qb->expr()->count('p'));
        return $qb->getQuery()->getSingleScalarResult();
    }
}
