<?php

namespace Keltanas\Bundle\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Keltanas\Bundle\UserBundle\Entity\User;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param User $user
     *
     * @return int
     */
    public function getCount(User $user = null)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select($qb->expr()->count('p'));
        if (null !== $user) {
            $qb->where('p.account = :user')->setParameter('user', $user->getId());
        }
        return $qb->getQuery()->getSingleScalarResult();
    }
}
