imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     %kernel.cache_dir%/data.sqlite

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path: "php://stdout"
            level: warning

swiftmailer:
    disable_delivery: true
