imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assets_version.php }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
#        assets_version_format: %%2$s/%%1$s
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        gravatar_hash: %gravatar_hash%
        google_analytics: %google_analytics%
        google_plus_id: %google_plus_id%
        disqus_shortname: %disqus_shortname%
#    form:
#        resources:
#            - "AcmeBundle:Form:form_div_layout.html.twig"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ "KeltanasPageBundle" ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"

        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        pngout:
            bin: "%kernel.root_dir%/Resources/pngout/pngout"

    assets:
        vendor_js:
            inputs:
                - %kernel.root_dir%/../web/bundles/keltanaspage/js/jquery-1.10.2.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js
            filters:
                - ?yui_js
            output: js/vendor.js

braincrafted_bootstrap:
    less_filter: less
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../web/bundles/keltanaspage/js/jquery-1.10.2.js
    auto_configure:
        assetic: false
        twig: false
        knp_menu: true
        knp_paginator: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Keltanas\UserBundle\Entity\User

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: false                # ensure distinct results, useful when ORM queries are using GROUP BY statements
                                       # надо отключить, чтобы работали составные ключи, или включить в PassController


knp_markdown:
    parser:
        service:              markdown.parser.max
    sundown:
        extensions:
            fenced_code_blocks:   true
            no_intra_emphasis:    false
            tables:               false
            autolink:             true
            strikethrough:        false
            lax_html_blocks:      false
            space_after_headers:  false
            superscript:          false
        render_flags:
            filter_html:          false
            no_images:            false
            no_links:             false
            no_styles:            false
            safe_links_only:      false
            with_toc_data:        false
            hard_wrap:            false
            xhtml:                false

keltanas_yandex_metrika:
    debug:  "%kernel.debug%"
    number: "%ya_tracking%"
    accurateTrackBounce: 10000
    clickmap: true
    params: ~
    ut: ~
    trackHash: true
    trackLinks: true
    webvisor: true

keltanas_page: ~
