security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 31536000 # 1 year in seconds
                path:     /

        dev:
            pattern:  ^/(_(profiler|wdt)|css|img|js)/
            security: false

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/register, roles: ROLE_ADMIN }
        - { path: ^/post/\d+/(edit|update|delete), roles: ROLE_ADMIN }
        - { path: ^/post/\d+, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/post/(create|new), roles: ROLE_USER }
        - { path: ^/post, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
