<?php

namespace keltanas\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;
use keltanas\UserBundle\Entity\User;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param User $user
     *
     * @return int
     */
    public function getCount(User $user = null)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select($qb->expr()->count('p'));
        if (null !== $user) {
            $qb->where('p.account = :user')->setParameter('user', $user->getId());
        }
        return $qb->getQuery()->getSingleScalarResult();
    }

    /**
     * @param $tagName
     *
     * @return \Doctrine\ORM\Query
     */
    public function getQueryForPaginator($tagName = null, User $user = null)
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.status = :status')
            ->setParameter('status', 1)
            ->orderBy('p.createdAt', 'desc')
        ;

        if (null !== $tagName) {
            $qb
                ->andWhere('p.tags LIKE :name')
                ->setParameter('name', '%'.$tagName.'%')
            ;
        }

        if (null !== $user) {
            $qb->where('p.account = :user')->setParameter('user', $user->getId());
        }

        $query = $qb->getQuery();

        $qb->select($qb->expr()->count('p'));
        $count = $qb->getQuery()->getSingleScalarResult();
        $query->setHint('knp_paginator.count', $count);
        return $query;
    }
}
