post:
    path:  /
    defaults: { _controller: "KeltanasPageBundle:Post:index" }

post_show:
    path:  /{id}
    defaults: { _controller: "KeltanasPageBundle:Post:show" }
    requirements: { id: \d+ }

post_edit:
    path:  /{id}/edit
    defaults: { _controller: "KeltanasPageBundle:Post:edit" }
    requirements: { id: \d+ }

post_update:
    path:  /{id}/update
    defaults: { _controller: "KeltanasPageBundle:Post:update" }
    requirements: { id: \d+, method: post|put }

post_delete:
    path:  /{id}/delete
    defaults: { _controller: "KeltanasPageBundle:Post:delete" }
    requirements: { id: \d+, method: get|post|delete }

post_new:
    path:  /new
    defaults: { _controller: "KeltanasPageBundle:Post:new" }

post_create:
    path:  /create
    defaults: { _controller: "KeltanasPageBundle:Post:create" }
    requirements: { method: post }

post_preview:
    path: /preview
    defaults: { _controller: "KeltanasPageBundle:Post:preview" }
    requirements: { method: post }
