post:
    pattern:  /
    defaults: { _controller: "keltanasPageBundle:Post:index" }

post_show:
    pattern:  /{id}
    defaults: { _controller: "keltanasPageBundle:Post:show" }
    requirements: { id: \d+ }

post_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "keltanasPageBundle:Post:edit" }
    requirements: { id: \d+ }

post_update:
    pattern:  /{id}/update
    defaults: { _controller: "keltanasPageBundle:Post:update" }
    requirements: { id: \d+, _method: post|put }

post_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "keltanasPageBundle:Post:delete" }
    requirements: { id: \d+, _method: get|post|delete }

post_new:
    pattern:  /new
    defaults: { _controller: "keltanasPageBundle:Post:new" }

post_create:
    pattern:  /create
    defaults: { _controller: "keltanasPageBundle:Post:create" }
    requirements: { _method: post }

post_preview:
    pattern: /preview/{id}
    defaults: { _controller: "keltanasPageBundle:Post:preview" }
    requirements: { _method: post }
